#ifndef _DONGLE_BEST3003_H_
#define _DONGLE_BEST3003_H_

typedef enum {
    DONGLE_NOTIFY_EVT_PLUGIN_GND_INFO,
    DONGLE_NOTIFY_EVT_PLUGIN_LOAD_INFO,    
    DONGLE_NOTIFY_EVT_PLUGOUT,
    DONGLE_NOTIFY_EVT_KEY_DN,
    DONGLE_NOTIFY_EVT_KEY_UP,
    DONGLE_NOTIFY_EVT_WAKEUP,
    DONGLE_NOTIFY_EVT_VOICE_CMD,

    EXT_HS_NOTIFY_EVT_NUM,
} DONGLE_NOTIFY_EVENT_E;

typedef enum {
    DONGLE_KEY_UNKNOWN,
    DONGLE_KEY_FUNC,
    DONGLE_KEY_VOL_PLUS,
    DONGLE_KEY_VOL_MINUS,

    DONGLE_KEY_NUM
} DONGLE_INFO_KEY_E;

typedef enum {
    DONGLE_EARPHONE_LOAD_UNKNOWN,
    DONGLE_EARPHONE_LOAD_16_OHM,
    DONGLE_EARPHONE_LOAD_32_OHM,
    DONGLE_EARPHONE_LOAD_600_OR_HIGHER_OHM,

    DONGLE_EARPHONE_LOAD_NUM
} DONGLE_INFO_EARPHONE_LOAD_TYPE;

typedef enum {
    DONGLE_EARPHONE_GND_UNKNOWN,
    DONGLE_EARPHONE_GND_POLE3_POLE4,    // no mic
    DONGLE_EARPHONE_GND_POLE3,  // CTIA: POLE3 for GND and POLE4 for MIC
    DONGLE_EARPHONE_GND_POLE4,  // OMTP: POLE3 for MIC and POLE4 for GND

    DONGLE_EARPHONE_GND_NUM
} DONGLE_INFO_EARPHONE_GND_TYPE;

typedef struct {
    uint8_t load_type:4;
    uint8_t gnd_type:4;
} DONGLE_INFO_EARPHONE_T;

typedef struct {
    DONGLE_INFO_EARPHONE_T earphone_info;   // used for EXT_HS_NOTIFY_EVT_PLUGIN
    DONGLE_INFO_KEY_E key_info;           // used for EXT_HS_NOTIFY_EVT_KEY_DN/EXT_HS_NOTIFY_EVT_KEY_UP
} DONGLE_INFORM_PARAM_T;

typedef void (*DONGLE_INFORM_CB) (DONGLE_NOTIFY_EVENT_E, DONGLE_INFORM_PARAM_T*);

typedef enum {
    DONGLE_GND_SENSING_AUTO,
    DONGLE_GND_SENSING_POLE3_POL4_FIXED,
    DONGLE_GND_SENSING_POLE3_FIXED,
    DONGLE_GND_SENSING_POLE4_FIXED,

    DONGLE_GND_SENSING_MODE_NUM
} DONGLE_CFG_GND_SENSING_MODE_E;

typedef enum {
    DONGLE_LOAD_SENSING_AUTO,
    DONGLE_LOAD_SENSING_16OHM_FIXED,
    DONGLE_LOAD_SENSING_32OHM_FIXED,
    DONGLE_LOAD_SENSING_600OHM_OR_HIGHER_FIXED,

    DONGLE_LOAD_SENSING_MODE_NUM
} DONGLE_CFG_LOAD_SENSING_MODE_E;

typedef struct {
    uint8_t cfg_low_level_for_plugin:1;
    uint8_t cfg_gnd_sensing_mode:2;
    uint8_t cfg_load_sensing_mode:2;
    uint8_t cfg_rsvd:3;

    DONGLE_INFORM_CB cb;
} DONGLE_CONFIG_T;



void dongle_open(const DONGLE_CONFIG_T* cfg);

#endif // _DONGLE_BEST3003_H_
